[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Ovo rešava problem sa MIME tipovima za JS module
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"
