backend:
  name: github
  repo: c3hic/kendic-fenster # Tvoj GitHub repozitorijum
  branch: main
  base_url: https://api.github.com

media_folder: "public/assets/promo"
public_folder: "/assets/promo"

collections:
  - name: "promo"
    label: "Promo Akcija"
    files:
      - label: "Podaci o akciji"
        name: "data"
        file: "src/data/promo.json"
        fields:
          - {label: "Aktivna (Prikaži na sajtu)", name: "active", widget: "boolean", default: true}
          - {label: "Tekst Akcije", name: "text", widget: "text", default: "Naručite danas, preuzmite za 24h!"}
          - {label: "Slika Akcije", name: "image", widget: "image", required: false}

  - name: "gallery"
    label: "Galerija Radova"
    files:
      - label: "Slike projekata"
        name: "data"
        file: "src/data/gallery.json"
        fields:
          - label: "Slike"
            name: "images"
            widget: "list"
            field: {label: "Slika", name: "image", widget: "image", media_folder: "public/assets/projects", public_folder: "/assets/projects"}
